[postgres]
user = 'postgres'
password = 'blaze2023'
database = 'master_db'
dbtable = 'tgt.mining_data'
url = 'db-data-accl-1.c8moakf5aght.us-east-1.rds.amazonaws.com'
port = '5432'

[postgres_ni]

host = "db-data-accl-1.c8moakf5aght.us-east-1.rds.amazonaws.com"
port = 5432
dbname = "master_db"
user = "postgres"
password = "blaze2023"